In [2]:
import pandas as pd
import numpy as np

In [5]:
sample_array = np.array(range(1, 6, 1))
print(sample_array)

[1 2 3 4 5]


In [6]:
sample_df = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array * 2,
    'col3' : ["A", "B", "C", "D", "F"]
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    F


In [7]:
# dfの結合
df_1 = pd.DataFrame({
    'col1': np.array([1,2,3]),
    'col2': np.array(["A","B","C"])
})

df_2 = pd.DataFrame({
    'col1': np.array([4,5,6]),
    'col2': np.array(["D","E","F"])
})

print(pd.concat([df_1, df_2]))
print(pd.concat([df_1, df_2], axis=1))


   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F
   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [11]:
# 列に対する操作
print(sample_df)
print()
print(sample_df.col2)
print()
print(sample_df["col2"])
print()
print(sample_df[['col2', 'col3']])

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    F

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    F


In [12]:
print(sample_df.drop("col1", axis=1))

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    F


In [17]:
# 行に対する操作
print(sample_df.head(n=3))
print()
print(sample_df.query("index == 0"))
print()
print(sample_df.query("col3 == 'B'"))
print()
print(sample_df.query("col3 == 'A' | col3 == 'D'"))
print()
print(sample_df.query("col3 == 'A' & col1 == 3"))

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C

   col1  col2 col3
0     1     2    A

   col1  col2 col3
1     2     4    B

   col1  col2 col3
0     1     2    A
3     4     8    D

Empty DataFrame
Columns: [col1, col2, col3]
Index: []


In [18]:
# 行も列にも条件
print(sample_df.query('col3 == "A"')[['col2', 'col3']])

   col2 col3
0     2    A


In [20]:
# データフレーム型 シリーズ型
print(type(sample_df))
print(type(sample_df.col1))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [22]:
print(type(np.array(sample_df.col1)))
print(type(sample_df['col1'].values))
print(type(sample_df.col1.values))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
import scipy as sp

In [24]:
%precision 3

'%.3f'

In [26]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
sp.sum(fish_data)

40

In [27]:
len(fish_data)

10

In [28]:
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.000

In [29]:
sp.mean(fish_data)

4.000

In [31]:
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.200

In [32]:
sp.var(fish_data, ddof=0)

1.200

In [33]:
# 不偏分散
sp.var(fish_data, ddof=1)

1.333

In [40]:
sigma = sp.sqrt(sp.var(fish_data, ddof=1))
sigma

1.155

In [38]:
sp.std(fish_data, ddof=1)

1.155

In [42]:
# 標準化
print(fish_data - mu)
print(fish_data - mu)
v = fish_data / sigma
print(v)
sp.std(v, ddof=1)

[-2. -1. -1.  0.  0.  0.  0.  1.  1.  2.]
[-2. -1. -1.  0.  0.  0.  0.  1.  1.  2.]
[1.732 2.598 2.598 3.464 3.464 3.464 3.464 4.33  4.33  5.196]


1.000

In [44]:
standard = (fish_data - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [45]:
sp.mean(standard)

0.000

In [46]:
sp.std(standard, ddof=1)

1.000

In [48]:
# max
print(sp.amax(fish_data))
# min
print(sp.amin(fish_data))
# median
print(sp.median(fish_data))

6
2
4.0


In [49]:
# scipyの統計分析特化のモジュール
from scipy import stats

In [52]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)
stats.scoreatpercentile(fish_data_3, 75)

7.000